id: n8n-config

info:
  name: N8n - Config
  author: icarot
  severity: medium
  description: |
    Detects if path /rest/settings of N8n web application is exposed, getting internal information. N8n is a Fair-code workflow automation platform with native AI capabilities.
  reference:
    - https://github.com/n8n-io/n8n
  classification:
    cpe: cpe:2.3:a:n8n:n8n:*:*:*:*:*:node.js:*:*
  metadata:
    max-request: 1
    vendor: n8n
    product: n8n
    shodan-query: http.html:"N8n"
  tags: n8n,config,exposed

http:
  - raw:
      - |
        GET /rest/settings HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'isDocker'
          - 'databaseType'
          - 'nodeJsVersion'
          - 'versionCli'
          - 'instanceId'
        condition: and

      - type: word
        part: content_type
        words:
          - 'application/json; charset=utf-8'

      - type: status
        status:
          - 200

    extractors:
      - type: json
        name: urlBaseEditor
        json:
          - '.data.urlBaseEditor'
      - type: json
        name: isDocker
        json:
          - '.data.isDocker'
      - type: json
        name: databaseType
        json:
          - '.data.databaseType'
      - type: json
        name: nodeJsVersion
        json:
          - '.data.nodeJsVersion'
      - type: json
        name: versionCli
        json:
          - '.data.versionCli'
      - type: json
        name: instanceId
        json:
          - '.data.instanceId'
      - type: json
        name: planName
        json:
          - '.data.license.planName'
      - type: json
        name: allowedModules
        json:
          - '.data.allowedModules'
