id: n8n-config

info:
  name: N8n - Config
  author: icarot
  severity: medium
  description: |
    The `/rest/settings` endpoint in N8n was publicly exposed, which could have disclosed internal configuration details and sensitive application information.
  reference:
    - https://github.com/n8n-io/n8n
  classification:
    cpe: cpe:2.3:a:n8n:n8n:*:*:*:*:*:node.js:*:*
  metadata:
    max-request: 1
    vendor: n8n
    product: n8n
    shodan-query: http.html:"N8n"
  tags: n8n,config,exposed

http:
  - raw:
      - |
        GET /rest/settings HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'isDocker'
          - 'databaseType'
          - 'nodeJsVersion'
          - 'versionCli'
          - 'instanceId'
        condition: and

      - type: word
        part: content_type
        words:
          - 'application/json'

      - type: status
        status:
          - 200
