id: openmetadata-admin-userenum

info:
  name: OpenMetadata - Admin User Enumeration
  author: icarot
  severity: info
  description: |
    Enumerates the admin users registered on OpenMetadata server.
  reference:
    - https://github.com/open-metadata/OpenMetadata
  classification:
    cpe: cpe:2.3:a:open-metadata:openmetadata:1.7.0:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: open-metadata
    product: openmetadata
    fofa-query: title="OpenMetadata"
    shodan-query: title:"OpenMetadata"
  tags: openmetadata,open-metadata,userenum

http:
  - raw:
      - |
        GET /api/v1/system/config/authorizer HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"adminPrincipals":'
          - '"principalDomain"'
        condition: and

      - type: word
        part: content_type
        words:
          - 'application/json'

      - type: status
        status:
          - 200
    extractors:
      - type: json
        name: adminUser
        json:
          - '.adminPrincipals'
      - type: json
        name: principalDomain
        json:
          - '.principalDomain'
      - type: json
        name: allowedDomains
        json:
          - '.allowedDomains'
