id: symfony-conflicting-headers-info-disclosure

info:
  name: Symfony Conflicting Trusted Headers Information Disclosure
  author: wakedxy
  severity: high
  description: |
    A misconfiguration in Symfony's trusted proxy and trusted headers settings 
    can trigger ConflictingHeadersException when both Forwarded and X-Forwarded-* headers 
    are supplied. If debug mode is enabled in production, this may expose sensitive 
    environment information such as SMTP credentials, application paths, and system configuration.
  reference:
    - https://symfony.com/doc/current/deployment/proxies.html
    - https://owasp.org/Top10/A05_2021-Security_Misconfiguration/
  tags: symfony,misconfiguration,exposure,headers

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    headers:
      Forwarded: "for=127.0.0.1;host=evil.com"
      X-Forwarded-Host: "evil.com"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Symfony\\Component\\HttpFoundation\\Exception\\ConflictingHeadersException"
        part: body

      - type: status
        status:
          - 500