id: api-inventory-swagger-openapi-graphql
info:
  name: API Inventory (Swagger/OpenAPI/GraphQL)
  author: Hamza Sahin
  severity: info
  description: |
    Locates common API documentation endpoints (Swagger UI / OpenAPI JSON) and GraphQL endpoints.
  tags: api,inventory,swagger,openapi,graphql

requests:
  - method: GET
    path:
      - "{{BaseURL}}/swagger.json"
      - "{{BaseURL}}/v3/api-docs"
      - "{{BaseURL}}/openapi.json"
      - "{{BaseURL}}/api-docs"
      - "{{BaseURL}}/swagger-ui.html"
      - "{{BaseURL}}/swagger"
      - "{{BaseURL}}/graphql"
      - "{{BaseURL}}/graphiql"
      - "{{BaseURL}}/playground"
    # herhangi biri eşleşsin
    matchers-condition: or
    matchers:
      # OpenAPI JSON (v2/v3)
      - type: regex
        part: body
        regex:
          - '(?i)"openapi"\\s*:\\s*"(3|2)\\.'
          - '(?i)"swagger"\\s*:\\s*"2\\.0"'
      # Swagger UI HTML
      - type: regex
        part: body
        regex:
          - '(?i)Swagger UI'
      # GraphQL endpoint (genel ipuçları; 200/400 olabilir)
      - type: regex
        part: body
        regex:
          - '(?i)GraphQL'
      # Status esnekliği (GraphQL bazen 400 döndürür)
      - type: status
        status: [200,400]
